spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bootjpa?useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    serialization:
      indent_output: true
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 123
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最下空闲
        min-idle: 0
server:
  port: 8888
